### ISSUE TITLE
没有运行

### ISSUE THREAD

**Issue by Xiaohantx** [KaiOrange/juejin-auto-checkin#21]
想要在北京时间17:22执行，所以设置了`- cron: "22 09 * * *"`看文档差8小时，但是到了时间也没有执行...

**Comment by Xiaohantx** [comment]
在17:35运行了

**Comment by KaiOrange** [comment]
到了执行时间的时候会开始执行action 期间有下载代码 安装node等操作 实际执行到代码那边大概有半个小时的时间差
