### ISSUE TITLE
[feat request] ：添加配置项

### ISSUE THREAD

**Issue by daiwa233** [KaiOrange/juejin-auto-checkin#4]
是否可以添加一些配置项，等矿石数量达到一定程度之后才开始抽奖

**Comment by KaiOrange** [comment]
现在每天会有一次的自动抽奖 用的是免费的额度 不会额外使用矿石去抽奖的

**Comment by KaiOrange** [comment]
@kouchao 小伙伴提了一个pull requests支持抽奖梭哈 每天把所有矿石都抽奖了 可以fork最新的代码体验一下
