### ISSUE TITLE
无法自动签到

### ISSUE THREAD

**Issue by CoderGFWu** [KaiOrange/juejin-auto-checkin#7]
我把里面时间改成2了， 应该是北京时间早上10点， 到了10点不会自动签到

**Comment by KaiOrange** [comment]
我看了一下 早上10点多已经执行了 这个10点的时候会开始执行脚本 包括clone代码、安装node、npm install、npm start等步骤 一顿操作下来大概持续20多分钟 也就是将近10点半的时候才会真正的执行
![image](https://user-images.githubusercontent.com/24317428/132674434-86647744-b3e0-4b8f-a662-94646ddf265b.png)

**Comment by CoderGFWu** [comment]
好的，感谢大佬解答
