### ISSUE TITLE
多个掘进账号怎么都自动抽签？

### ISSUE THREAD

**Issue by icingGitHub** [KaiOrange/juejin-auto-checkin#9]

**Comment by icingGitHub** [comment]
..恭喜啥




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KaiOrange/juejin-auto-checkin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月11日(星期一) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KaiOrange/juejin-auto-checkin] 多个掘进账号怎么都自动抽签？ (#9)





 
目前还不支持多个账号，如果你有多个github账号的话，那么恭喜你了😁
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KaiOrange** [comment]
如果有多个github账号可以多fork几个，目前还不支持多掘金账号自动签到。

**Comment by AlexV525** [comment]
把 job 复制几次，用不同的 cookie 就可以了

**Comment by KaiOrange** [comment]
上楼正解

**Comment by fadeds** [comment]
外层加个循环  不就可以了
